####################################################################################################
# MYSQL
####################################################################################################
mysql:
  image: mysql:5.7
  container_name: presence_database
  ports:
    - "3307:3306"
  volumes:
    - ./image/mysql/data/:/var/lib/mysql/:rw
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: lumen
    MYSQL_USER: lumen
    MYSQL_PASSWORD: secret
    MYSQL_ROOT_HOST: 172.*.*.*

####################################################################################################
# API
####################################################################################################
presence_api:
  build: ./www/api/
  container_name: presence_api
  ports:
    - "9000:9000"
  links:
    - mysql
  volumes:
    - ./image/api/:/var/www/html/storage/:rw
  environment:
    APP_KEY: AAAAAAAAAABBBBBBBBBBCCCCCCCCCCDD
    APP_DEBUG: false

    JWT_SECRET: SECRET_KEY

    DB_CONNECTION: mysql
    DB_HOST: mysql
    DB_DATABASE: lumen
    DB_USERNAME: lumen
    DB_PASSWORD: secret

####################################################################################################
# APP
####################################################################################################
presence_app:
  build: ./www/app/
  container_name: presence_app
  ports:
    - "9001:80"
  environment:
    #API_PATH: http://192.52.34.132/api
    API_PATH: http://localhost/api
    APP_NAME: Presence

####################################################################################################
# NGINX
####################################################################################################
nginx:
  image: nginx:latest
  container_name: webserver
  ports:
    - 80:80
  volumes:
    - ./image/nginx/default.conf:/etc/nginx/conf.d/default.conf
  links:
    - presence_api
    - presence_app
